### ISSUE TITLE
Relay-Addon

### ISSUE THREAD

**Issue by mawa85** [wladwnt/wled#2]
I noticed the WS2815 draw lots of power even when switched off (~10W for my 7m strip).
Any plans to add a controllable Relay to the board to cut power to the strip?
e.g. https://www.aliexpress.com/item/1005001714620325.html
Thanks

**Comment by wladwnt** [comment]
No. The reason is that high standby consumption is only the issue of 12V LED. Here the relay makes sense. For 5V however, the relay is rather a bed idea. It can carry only approximately 10A continously and therefore will limit the power to 50W, so only about 200 LEDs might be then used with the controller. Plus it makes the controller bigger, relays fails often and consume power during operation.
